#!/usr/bin/env bash
set -euo pipefail

print_help() {
  cat <<-EOF
	Checks that API pricing covers cycle costs.

	For each API method, this:
	* Gets the canister cycles balance
	* Makes a sample API call
	* Gets the cycles balance again
	* Reports on the difference.

	Note: Measurement is affected by other API calls made to the network.

	Usage: "$(basename "$0")" [network] [method_name_pattern]
	where:
	  'network' is a dfx network name.
	     Default: ic
	  'method_name_pattern' is a regular expression; only API methods
	     matching the pattern will be tested.
	     Default: All methods.
	Example:
	  "$(basename "$0")" ic btc
	     will check pricing for all bitcoin methods.
	EOF
}

[[ "${1:-}" != "--help" ]] || {
  print_help
  exit 0
}

DFX_NETWORK="${1:-ic}"
METHOD_NAME_PATTERN="${2:-.}"
CANISTER_ID="$(dfx canister id --network "$DFX_NETWORK" icrc-factory)"
LOG_FILE="check-pricing.${DFX_NETWORK}.$(date --iso-8601=second).jsonl"

to_number() {
  : Converts symbols such as 1K to 1_000
  numfmt --from=si | rev | sed 's/.../&_/g' | rev
}

canister_balance() {
  dfx canister status --network "$DFX_NETWORK" icrc-factory | awk '($1 == "Balance:"){print $2}'
}

add_underscores_to_number() {
  rev | sed -E 's/.../&_/g;s/_(-?)$/\1/g' | rev
}

remove_underscores() {
  tr -d _
}

check_call_pricing() {
  local before after method_name
  echo "$1" | grep -qE "$METHOD_NAME_PATTERN" || {
    echo "Skipping $1..."
    return
  }
  method_name="$1"
  before="$(canister_balance)"
  dfx canister call --network "$DFX_NETWORK" icrc-factory "${@}" >/dev/null
  after="$(canister_balance)"
  diff="$(echo "$after - $before" | remove_underscores | bc | add_underscores_to_number)"
  if [[ $diff = -* ]]; then
    echo "WARNING: canister balance fell by $diff for: $1"
  else
    echo "OK: canister balance rose by $diff for: $1"
  fi
  (
    export before after diff method_name
    jq --null-input '{
      method_name: $ENV.method_name,
      cycles_balance_before: ($ENV.before | gsub("_";"") | tonumber),
      cycles_balance_after: ($ENV.after | gsub("_";"") | tonumber),
      diff: ($ENV.diff | gsub("_";"") | tonumber)
    }' >>"$LOG_FILE"
  )
}

APPROVAL="1P"

: Approve funds for use in the test
dfx canister call cycles_ledger icrc2_approve --network "$DFX_NETWORK" "
  record {
    amount = $(echo "$APPROVAL" | to_number);
    spender = record {
      owner = principal \"${CANISTER_ID}\";
    };
  }" >/dev/null

: Check that each method is making a profit

check_call_pricing create_icrc_ledger '
(
  record {
    symbol = null;
    name = null;
    transfer_fee = null;
    decimals = null;
    minting_account = null
  },
  opt variant { CallerPaysIcrc2Cycles },
)
'
