#!/usr/bin/env bash
set -euo pipefail
# Lint the Rust canister code, excluding the autogenerated crates.
for crate in src/icrc-factory/Cargo.toml; do
  cargo clippy --manifest-path "$crate" --locked --target wasm32-unknown-unknown --all-features
done
